version: '3.1'

services:
  codrr_sls_pg:
    image: postgres:15.1
    container_name: codrr_sls_pg
    restart: always
    environment:
      POSTGRES_DB: codrrslsdb
      POSTGRES_USER: uslscodrr
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5436:5432