service: curso-sls-nodejs-ts
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
  environment: ${file(./src/config/environment.yml):env.${self:custom.stage}}
functions:
  # Here your functions
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-localstack
package:
  exclude:
    - node_modules/**/*
  include: handler.ts
custom:
  stage: '${opt:stage, "local"}'
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: false
    lambda:
      mountCode: True
    docker:
      sudo: False
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node14"
    define: { "require.resolve": undefined }
    platform: "node"
    concurrency: 10
