service: curso-sls-nodejs-ts
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: "${param:prof,null}"
  environment: ${file(./src/config/environment.yml):env.${self:custom.stage}}
functions:
  - ${file(./src/functions.yml)}
plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-localstack

custom:
  stage: '${opt:stage, "local"}'
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    autostart: false
    lambda:
      mountCode: True
    docker:
      sudo: False
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: "node18"
    concurrency: 10
